version: '3'

services:
  ifcbdb:
    image: ${IFCBDB_IMAGE:-whoi/ifcb-dashboard:latest}
    container_name: ifcbdb
    environment:
      - NGINX_HOST=${HOST:-localhost}
      - NGINX_HTTP_PORT=${HTTP_PORT:-80}
      - NGINX_HTTPS_PORT=${HTTPS_PORT:-443}
      - DEFAULT_DATASET=${DEFAULT_DATASET:-}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-changeme}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ifcb}
    volumes:
      - nginx-static:/static
      - ${PRIMARY_DATA_DIR:-./ifcb_data}:/data
      - ${LOCAL_SETTINGS:-/dev/null}:/ifcbdb/ifcbdb/local_settings.py
    networks:
      - nginx_network
      - postgres_network
      - memcached_network
      - redis_network
    depends_on:
      - postgres
      - memcached
      - redis
    restart: unless-stopped

  celery:
    image: ${IFCBDB_IMAGE:-whoi/ifcb-dashboard:latest}
    container_name: celery
    command: celery -A ifcbdb worker -l info
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-changeme}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ifcb}
    volumes:
      - ${PRIMARY_DATA_DIR:-./ifcb_data}:/data
      - ${LOCAL_SETTINGS:-/dev/null}:/ifcbdb/ifcbdb/local_settings.py
    depends_on:
      - postgres
      - memcached
      - redis
    networks:
      - redis_network
      - postgres_network
      - memcached_network
    restart: unless-stopped

  nginx:
    image: ${NGINX_IMAGE:-nginx:1.25}
    container_name: nginx
    environment:
      - NGINX_HOST=${HOST:-localhost}
      - NGINX_HTTP_PORT=${HTTP_PORT:-80}
      - NGINX_HTTPS_PORT=${HTTPS_PORT:-443}
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - ${NGINX_TEMPLATE:-./nginx-ssl.conf.template}:/etc/nginx/templates/default.conf.template
      - nginx-static:/static
      - ${SSL_KEY}:/ssl/no-pass-key.pem:ro
      - ${SSL_CERT}:/ssl/cert.pem:ro
    depends_on:
      - ifcbdb
    networks:
      - nginx_network
    restart: unless-stopped

  postgres:
    image: ${POSTGIS_IMAGE:-postgis/postgis:16-3.4}
    container_name: postgres
    environment:
      - POSTGRES_USER=ifcb
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ifcb}
      - POSTGRES_DB=ifcb
    volumes:
      - ifcbdb-postgis-data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: unless-stopped

  memcached:
    image: ${MEMCACHED_IMAGE:-memcached:1.6}
    container_name: memcached
    command: ["-m", "64m"]
    networks:
      - memcached_network
    restart: unless-stopped

  redis:
    image: ${REDIS_IMAGE:-redis:7.2}
    container_name: redis
    networks:
      - redis_network
    restart: unless-stopped

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge
  memcached_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  ifcbdb-postgis-data:
    name: ${POSTGIS_VOLUME:-ifcbdb-postgis-data}
  nginx-static:
    name: ${NGINX_STATIC_VOLUME:-ifcbdb-nginx-static}
